# Generated by Django 3.1.7 on 2021-03-20 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='language_types',
            fields=[
                ('language_name', models.CharField(max_length=50)),
                ('language_value', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='suggestions',
            fields=[
                ('suggestor_name', models.CharField(default='anonymous', max_length=50)),
                ('suggestion', models.CharField(default='', max_length=200)),
                ('suggestion_value', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='tutorial_types',
            fields=[
                ('type_name', models.CharField(max_length=50)),
                ('type_value', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='user_infos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=50)),
                ('pass_user', models.CharField(default='', max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='tutorials_paths',
            fields=[
                ('links_name', models.CharField(blank=True, max_length=70)),
                ('links_path', models.CharField(blank=True, max_length=300)),
                ('links_val', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('categ_name', models.CharField(blank=True, max_length=100)),
                ('language_type', models.CharField(blank=True, max_length=100)),
                ('language_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.language_types')),
                ('type_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tutorial_types')),
            ],
        ),
    ]
