# Generated by Django 3.1.7 on 2021-03-16 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='language_type',
            fields=[
                ('language_name', models.CharField(max_length=50)),
                ('language_value', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='suggestion',
            fields=[
                ('suggestor_name', models.CharField(default='anonymous', max_length=50)),
                ('suggestion', models.CharField(default='', max_length=200)),
                ('suggestion_value', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='tutorial_type',
            fields=[
                ('type_name', models.CharField(max_length=50)),
                ('type_value', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=50)),
                ('pass_user', models.CharField(default='', max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='links_db',
            fields=[
                ('links_path', models.CharField(default='', max_length=70)),
                ('links_val', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('language_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.language_type')),
                ('type_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tutorial_type')),
            ],
        ),
    ]
